### PR TITLE
feat: enable multiple files in the same yjs doc

### PR DESCRIPTION
**Pull request by zjkmxy**
-   [X] I read the contributing guide 
-   [X] I agree to follow the code of conduct 

## Summary

In current `plugin-collab`, the path to the XML fragment in the Yjs doc is hard-coded to `'prosemirror'`, which makes it impossible to put multiple Milkdown documents in the same Yjs document.
Since `y-prosemirror` has deprecated `yDocToProsemirror` for `yXmlFragmentToProseMirrorRootNode`, I move from `Y.Doc` & hard-coded path to user-provided `Y.XmlFragment`.

## How did you test this change?

Tested with storybook page.

### CODE REVIEW

**Comment by Saul-Mirone** [comment]
I think the collab plugin should not be included in the crepe package because users may want to use different packages for collaborative editing, for example the prosemirror official one or loro.

**Comment by zjkmxy** [comment]
> I think the collab plugin should not be included in the crepe package because users may want to use different packages for collaborative editing, for example the prosemirror official one or loro.

Make sense. Let me update the plugin only without touching other things.

**Comment by zjkmxy** [comment]
I have undone the unnecessary changes. There are two changes outside of the plugin because my local compiler does not allow me to build without them:

`packages/crepe/src/feature/block-edit/handle/index.ts`:

It complains that `this.#content.addIcon` does not accept `undefined`.

`packages/prose/src/toolkit/input-rules/custom-input-rules.ts`:

It complains `rules[i]` maybe `undefined` and thus cannot be converted to `{ match: RegExp }`.

Please let me know if I need also to undo these.

**Comment by Saul-Mirone** [comment]
The rest part looks good to me, thanks for contribution!

**Pull request merged**
